### ISSUE TITLE
upsert/merge wont work with postgres

### ISSUE THREAD

**Issue by mren** [snd/mohair#10]
[upsert](http://en.wikipedia.org/wiki/Upsert)

currently only the mysql special syntax `ON DUPLICATE KEY UPDATE` is supported

[some reference on stackoverflow on this topic](http://stackoverflow.com/questions/1109061/insert-on-duplicate-update-postgresql)

**Comment by tsouza** [comment]
Hi there,

What happened with this feature? Can't see it in master...

Thanks

**Comment by snd** [comment]
hi thiago,

this issue is from before the rewrite where the api and goal of mohair changed a lot (version 0.8).

upsert differs from mysql to postgres.
we are using mohair in some projects using postgres and in some legacy projects using mysql.
i decided to keep mohair free from database specific extensions to sql.

after talking to mren about it in person i closed the issue.
i should have documented it here.

if you really need it feel free to write me and reopen the issue.
i will then look into seperating mysql specific features from the core and adding clean support for upsert.

**Comment by tsouza** [comment]
Hello there,

Thanks for your feedback! I understand that this is implementation specific and could be dangerous if a project needs portability. I'll try to implement this using transactions in standard way.

Thanks
