### ISSUE TITLE
Version 0.11.1 doesn't have compiled JS in the package

### ISSUE THREAD

**Issue by szymonrw** [snd/mohair#27]
I've just installed mohair 0.11.1 and when I've tried to `require` it, I've got:

```
> require("mohair")
Error: Cannot find module 'mohair'
…
```

Quick investigation and it turns out that `node_modules/mohair/src` contains only `coffee` files. For some reason the `prepublish` script was not run or failed silently I guess.

0.11.0 has those JavaScript files in place.

**Comment by snd** [comment]
thanks for spotting that!

i noticed some problems when i published that version.

i now tried to force publish and unpublish & publish it.
both didn't work because of this: https://github.com/npm/npm/issues/4588

i am using node-0.10.25 / npm-1.3.24.

will keep you updated when i manage to publish 0.11.1 correctly with the javascript files in place!

**Comment by snd** [comment]
i just bumped the version to 0.11.2

it worked and contains the js files.

**Comment by szymonrw** [comment]
That was quick! Thanks :-)
